"use client";

/**
 * ReportView renders a ReportDoc as an "executive document": serif body,
 * narrow column, sky-500 accents only on H1 underline. Same component is
 * used for the on-screen preview and the standalone HTML download — the
 * download path simply serializes the rendered DOM with inline styles.
 */

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { ReportDoc, ReportSection } from "@/lib/api";

const SNIPPET_LABEL: Record<string, string> = {
  analysis: "Analysis code",
  sql: "SQL",
  chart: "Chart code",
};

function Section({ index, section }: { index: number; section: ReportSection }) {
  return (
    <section className="report-section">
      <h2>
        <span className="report-section-number">{index}.</span>{" "}
        {section.question || "Finding"}
      </h2>
      <div className="report-body">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{section.bodyMd}</ReactMarkdown>
      </div>
      {section.charts.map((c) => (
        <figure key={c.id} className="report-figure">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={c.dataUrl} alt={c.title || "chart"} />
          {c.title ? <figcaption>{c.title}</figcaption> : null}
        </figure>
      ))}
      {section.snippets.length > 0 ? (
        <details className="report-snippets">
          <summary>Methodology · code used to compute this finding</summary>
          {section.snippets.map((s) => (
            <div key={s.id} className="report-snippet">
              <p className="report-snippet-label">
                {SNIPPET_LABEL[s.type] ?? s.type}
              </p>
              <pre>
                <code>{s.code}</code>
              </pre>
            </div>
          ))}
        </details>
      ) : null}
    </section>
  );
}

export function ReportView({
  report,
  title,
  subtitle,
  author,
}: {
  report: ReportDoc;
  title: string;
  subtitle?: string;
  author?: string;
}) {
  const formattedDate = new Date(report.generatedAt).toLocaleDateString(
    undefined,
    { year: "numeric", month: "long", day: "numeric" },
  );
  return (
    <article className="report-doc">
      <header className="report-header">
        <h1>{title}</h1>
        {subtitle ? <p className="report-subtitle">{subtitle}</p> : null}
        <p className="report-meta">
          {author ? `${author} · ` : ""}
          {formattedDate} · Dataset:{" "}
          <span className="report-dataset">{report.datasetName}</span>{" "}
          ({report.datasetMeta.rowCount.toLocaleString()} rows ·{" "}
          {report.datasetMeta.columns.length} columns)
        </p>
      </header>
      {report.sections.length === 0 ? (
        <p className="report-empty">
          No findings pinned. Pin at least one assistant turn in the chat to
          include it here.
        </p>
      ) : (
        report.sections.map((s, i) => (
          <Section key={s.id} index={i + 1} section={s} />
        ))
      )}
      <footer className="report-footer">
        <p>Generated by Data Analyst</p>
      </footer>
    </article>
  );
}

/**
 * Inline CSS for the report. Kept as a string so the download flow can
 * embed it verbatim into the standalone HTML file.
 */
export const REPORT_STYLES = `
  body {
    margin: 0;
    background: #fafafa;
  }
  .report-doc {
    max-width: 720px;
    margin: 48px auto;
    padding: 56px 64px;
    background: #ffffff;
    color: #1c1c1c;
    font-family: Georgia, "Source Serif Pro", "Iowan Old Style", serif;
    font-size: 16px;
    line-height: 1.7;
    border-radius: 6px;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
  }
  .report-header {
    margin-bottom: 40px;
    padding-bottom: 24px;
    border-bottom: 2px solid #0ea5e9;
  }
  .report-header h1 {
    margin: 0 0 8px 0;
    font-size: 32px;
    font-weight: 700;
    letter-spacing: -0.01em;
    color: #0c0c0c;
  }
  .report-subtitle {
    margin: 4px 0 16px 0;
    font-size: 17px;
    color: #555;
    font-style: italic;
  }
  .report-meta {
    margin: 0;
    font-size: 13px;
    color: #777;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  .report-dataset {
    color: #0ea5e9;
    font-weight: 600;
  }
  .report-section {
    margin-bottom: 36px;
  }
  .report-section h2 {
    font-size: 22px;
    font-weight: 600;
    margin: 32px 0 12px 0;
    color: #1c1c1c;
  }
  .report-section-number {
    color: #0ea5e9;
    font-weight: 700;
  }
  .report-body p {
    margin: 0.7em 0;
  }
  .report-body ul, .report-body ol {
    padding-left: 24px;
    margin: 0.7em 0;
  }
  .report-body code {
    font-family: "SF Mono", Menlo, Consolas, monospace;
    font-size: 0.92em;
    background: #f4f4f4;
    padding: 1px 5px;
    border-radius: 3px;
  }
  .report-body strong { color: #0c0c0c; }
  .report-figure {
    margin: 20px 0;
    text-align: center;
  }
  .report-figure img {
    max-width: 100%;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
  }
  .report-figure figcaption {
    margin-top: 8px;
    font-size: 13px;
    color: #777;
    font-style: italic;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  .report-snippets {
    margin-top: 16px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size: 13px;
  }
  .report-snippets > summary {
    cursor: pointer;
    color: #777;
    user-select: none;
    margin-bottom: 8px;
  }
  .report-snippet { margin-top: 12px; }
  .report-snippet-label {
    margin: 0 0 4px 0;
    font-weight: 600;
    color: #555;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }
  .report-snippet pre {
    background: #f7f7f7;
    border: 1px solid #ececec;
    border-radius: 4px;
    padding: 12px 14px;
    font-family: "SF Mono", Menlo, Consolas, monospace;
    font-size: 12.5px;
    overflow-x: auto;
    margin: 0;
  }
  .report-empty {
    color: #999;
    font-style: italic;
    text-align: center;
    padding: 32px 0;
  }
  .report-footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #ececec;
    color: #999;
    font-size: 12px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    text-align: center;
  }
`;

/** Build a standalone HTML document string from a rendered report root. */
export function reportToStandaloneHTML(
  rootHTML: string,
  title: string,
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<meta name="generator" content="Data Analyst">
<style>${REPORT_STYLES}</style>
</head>
<body>${rootHTML}</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
